services:
  - type: web
    name: realroutereviews-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd api && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_NAME
        value: neondb
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        value: ep-yellow-bar-a5htbtp4-pooler.us-east-2.aws.neon.tech
      - key: DB_PORT
        value: 5432